packages:
    - packages/*

catalog:
    "@internationalized/date": ">=3.10.0"
    "@types/node": ^24.10.2
    "@types/react": ">=19.2.7"
    "@types/react-dom": ">=19.2.3"
    next: ">=16.0.7"
    react: ">=19.2.1"
    react-dom: ">=19.2.1"
    tailwindcss: "^3.4.19"
    typescript: ">=5.8.3"
