packages:
    # all packages in direct subdirs of packages/
    - "packages/*"

catalog:
    "@types/react": ">=19.2.4"
    "@types/react-dom": ">=19.2.3"
    react: ">=19.2.0"
    react-dom: ">=19.2.0"
    typescript: ">=5.8.3"
