export { NiceSearch } from "@/components/NiceSearch"
export type { NiceSearchProps } from "@/components/NiceSearch"
export { Theme } from "@/components/Theme"
export type { ComponentsConfig, ThemeComponentProps, ThemeMap } from "@/components/Theme"
export { useScrollY } from "@/hooks/useScrollY"
export type { UseScrollYOptions } from "@/hooks/useScrollY"
